### ISSUE TITLE
The config of only using copypaste

### ISSUE THREAD

**Issue by leaf1170124460** [yoctta/XPaste#5]
Hi, @yoctta.
Thanks for your work on XPaste.

How should I modify the config file if I want to only use copypaste? I set `INPUT.USE_COPY_METHOD` to `self_copy`, but I am not sure the `INPUT.INST_POOL` should be `false` or `true` ?

The modified config file is: 
```
_BASE_: "./Base-C2_L_R5021k_640b64_4x.yaml"
MODEL:
  ROI_BOX_HEAD:
    USE_ZEROSHOT_CLS: false
    FED_LOSS_FREQ_WEIGHT: 0.5
  WEIGHTS: "models/swin_large_patch4_window12_384_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: L-22k-384
  FPN:
    IN_FEATURES: ["swin1", "swin2", "swin3"]
SOLVER:
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  MODEL_EMA: 0.999
DATASETS:
  TRAIN: ("lvis_v1_train",)
  TEST: ("lvis_v1_val",)

INPUT:
  INST_POOL: true
  INST_POOL_PATH: "/mnt/data/LVIS_instance_pools.json"
  INST_POOL_FORMAT: "RGBA"
  USE_COPY_METHOD: "self_copy"
  USE_INSTABOOST: false
  MASK_FORMAT: bitmask
  CP_METHOD: ['basic']
  RANDOM_ROTATE: false
  INST_POOL_SAMPLE_TYPE: "cas_random"
  TRAIN_SIZE: 896
```
