### ISSUE TITLE
How to reproduce results on COCO ?

### ISSUE THREAD

**Issue by Z-MU-Z** [yoctta/XPaste#6]
As I didn't see the config, Can I only change lvis_v1_train to coco_2017_train, as below?
```
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  # SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  # REPEAT_THRESHOLD: 0.001
  NUM_WORKERS: 8
TEST:
  DETECTIONS_PER_IMAGE: 100
```

**Comment by Z-MU-Z** [comment]
When I used copy-paste on COCO, I was very surprised to find that the performance would instead decrease. This is my config for coco baseline.
```
MODEL:
  META_ARCHITECTURE: "CustomRCNN"
  MASK_ON: True
  PROPOSAL_GENERATOR:
    NAME: "CenterNet"
  WEIGHTS: "models/resnet50_miil_21k.pkl"
  BACKBONE:
    NAME: build_p67_timm_fpn_backbone
  TIMM:
    BASE_NAME: resnet50_in21k
  FPN:
    IN_FEATURES: ["layer3", "layer4", "layer5"]
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  ROI_HEADS:
    NAME: DeticCascadeROIHeads
    IN_FEATURES: ["p3", "p4", "p5"]
    IOU_THRESHOLDS: [0.6]
    NUM_CLASSES: 80
    SCORE_THRESH_TEST: 0.02
    NMS_THRESH_TEST: 0.5
  ROI_BOX_CASCADE_HEAD:
    IOUS: [0.6, 0.7, 0.8]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    CLS_AGNOSTIC_BBOX_REG: True
    MULT_PROPOSAL_SCORE: True

    USE_SIGMOID_CE: True
    USE_FED_LOSS: False # for coco
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    CLS_AGNOSTIC_MASK: True
  CENTERNET:
    NUM_CLASSES: 1203
    REG_WEIGHT: 1.
    NOT_NORM_REG: True
    ONLY_PROPOSAL: True
    WITH_AGN_HM: True
    INFERENCE_TH: 0.0001
    PRE_NMS_TOPK_TRAIN: 4000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TEST: 256
    NMS_TH_TRAIN: 0.9
    NMS_TH_TEST: 0.9
    POS_WEIGHT: 0.5
    NEG_WEIGHT: 0.5
    IGNORE_HIGH_FP: 0.85
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  # SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  # REPEAT_THRESHOLD: 0.001
  NUM_WORKERS: 8
TEST:
  DETECTIONS_PER_IMAGE: 100
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 10000
  WARMUP_FACTOR: 0.0001
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: "ADAMW"
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
  BASE_LR: 0.0002
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 640
OUTPUT_DIR: "./output/auto"
EVAL_PROPOSAL_AR: False
VERSION: 2
FP16: True
```
[09/12 00:01:59] d2.evaluation.testing INFO: copypaste: Task: bbox
[09/12 00:01:59] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
[09/12 00:01:59] d2.evaluation.testing INFO: copypaste: 44.1037,62.7251,47.5606,29.8676,48.4812,56.0459
[09/12 00:01:59] d2.evaluation.testing INFO: copypaste: Task: segm
[09/12 00:01:59] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
[09/12 00:01:59] d2.evaluation.testing INFO: copypaste: 38.2580,59.5906,41.2227,21.4642,42.3805,52.5607
and for copy-paste , config is below

```
_BASE_: "./Base-C2_L_R5021k_640b16_1x_COCO.yaml"



INPUT:
  INST_POOL: true
  INST_POOL_PATH: "datasets/lvis/lvis_xpaste100/LVIS_instance_pools.json"
  INST_POOL_FORMAT: "RGBA"
  USE_COPY_METHOD: "self_copy"
  USE_INSTABOOST: false
  MASK_FORMAT: bitmask
  CP_METHOD: ['basic']
  RANDOM_ROTATE: false
  INST_POOL_SAMPLE_TYPE: "cas_random"
  TRAIN_SIZE: 640


```

[09/12 01:30:08] d2.evaluation.testing INFO: copypaste: Task: bbox
[09/12 01:30:08] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
[09/12 01:30:08] d2.evaluation.testing INFO: copypaste: 43.9764,62.3777,47.2861,28.6399,48.2917,56.5546
[09/12 01:30:08] d2.evaluation.testing INFO: copypaste: Task: segm
[09/12 01:30:08] d2.evaluation.testing INFO: copypaste: AP,AP50,AP75,APs,APm,APl
[09/12 01:30:08] d2.evaluation.testing INFO: copypaste: 38.0468,59.3249,40.9244,21.5744,41.7649,53.0507
